/// Madina Mushaf (QCF V1) layout, generated by
/// `tool/generate_mushaf_layout.dart` into `assets/quran/mushaf_layout.json`.
class MushafLayout {
  const MushafLayout({required this.chapters, required this.pages});

  final List<MushafChapter> chapters;
  final List<MushafPage> pages;

  factory MushafLayout.fromJson(Map<String, dynamic> json) {
    return MushafLayout(
      chapters: (json['chapters'] as List)
          .map((e) => MushafChapter.fromJson(e as List))
          .toList(growable: false),
      pages: [
        for (final (index, page) in (json['pages'] as List).indexed)
          MushafPage.fromJson(index + 1, page as Map<String, dynamic>),
      ],
    );
  }
}

class MushafChapter {
  const MushafChapter({
    required this.number,
    required this.name,
    required this.startPage,
    required this.isMeccan,
    required this.versesCount,
  });

  final int number;
  final String name;
  final int startPage;
  final bool isMeccan;
  final int versesCount;

  factory MushafChapter.fromJson(List json) {
    return MushafChapter(
      number: json[0] as int,
      name: json[1] as String,
      startPage: json[2] as int,
      isMeccan: json[3] == 'makkah',
      versesCount: json[4] as int,
    );
  }
}

class MushafPage {
  const MushafPage({
    required this.number,
    required this.juz,
    required this.lines,
  });

  final int number;
  final int juz;
  final List<MushafLine> lines;

  /// Pages 1 and 2 (Al-Fatiha, start of Al-Baqarah) are centered, not justified.
  bool get isCentered => number <= 2;

  /// The surah the page opens with.
  int get firstSurah {
    for (final line in lines) {
      if (line is MushafWordsLine) return line.words.first.surah;
      if (line is MushafSurahHeaderLine) return line.surah;
    }
    return 1;
  }

  factory MushafPage.fromJson(int number, Map<String, dynamic> json) {
    return MushafPage(
      number: number,
      juz: json['j'] as int,
      lines: (json['l'] as List)
          .map((e) => MushafLine.fromJson(e as Map<String, dynamic>))
          .toList(growable: false),
    );
  }
}

sealed class MushafLine {
  const MushafLine();

  factory MushafLine.fromJson(Map<String, dynamic> json) {
    if (json['w'] case final List words) {
      return MushafWordsLine(
        words
            .map((e) => MushafWord.fromJson(e as List))
            .toList(growable: false),
      );
    }
    if (json['h'] case final int surah) return MushafSurahHeaderLine(surah);
    return const MushafBismillahLine();
  }
}

class MushafWordsLine extends MushafLine {
  const MushafWordsLine(this.words);

  final List<MushafWord> words;
}

class MushafSurahHeaderLine extends MushafLine {
  const MushafSurahHeaderLine(this.surah);

  final int surah;
}

class MushafBismillahLine extends MushafLine {
  const MushafBismillahLine();
}

class MushafWord {
  const MushafWord({
    required this.code,
    required this.surah,
    required this.ayah,
    required this.isEnd,
  });

  /// Glyph in the page's QCF V1 font.
  final String code;
  final int surah;
  final int ayah;

  /// True for the end-of-ayah marker (the ayah number medallion).
  final bool isEnd;

  String get verseKey => '$surah:$ayah';

  factory MushafWord.fromJson(List json) {
    return MushafWord(
      code: json[0] as String,
      surah: json[1] as int,
      ayah: json[2] as int,
      isEnd: json[3] == 1,
    );
  }
}
